# ---------Products STOCKS------------------

Product.create!(
  ticker: "XOM",
  name: "Exxon Mobil", Corporation: "",
  description: "",
  sector: "",
  product_type:,
  esg_score: 1173,
  er_score: 538,
  sr_score: 322,
  gr_score: 313
)

Product.create!(
  ticker: "TSLA",
  name: "Tesla, Inc.",
  description: "Tesla, Inc. is an American electric vehicle and clean energy company based in Palo Alto, California. Tesla's current products include electric cars, battery energy storage from home to grid-scale, solar panels and solar roof tiles, as well as other related products and services. In 2020, Tesla had the highest sales in the plug-in and battery electric passenger car segments, capturing 16% of the plug-in market (which includes plug-in hybrids) and 23% of the battery-electric (purely electric) market. Through its subsidiary Tesla Energy, the company develops and is a major installer of solar photovoltaic energy generation systems in the United States. Tesla Energy is also one of the largest global suppliers of battery energy storage systems, with 3 GWh of battery storage supplied in 2020.",
  sector: "MANUFACTURING",
  product_type:,
  esg_score: 993,
  er_score: 555,
  sr_score: 160,
  gr_score: 278
)


Product.create!(
  ticker: "IBM",
  name: "International Business Machines",
  description: "International Business Machines Corporation (IBM) is an American multinational technology company headquartered in Armonk, New York, with operations in over 170 countries. The company began in 1911, founded in Endicott, New York, as the Computing-Tabulating-Recording Company (CTR) and was renamed International Business Machines in 1924. IBM is incorporated in New York. IBM produces and sells computer hardware, middleware and software, and provides hosting and consulting services in areas ranging from mainframe computers to nanotechnology. IBM is also a major research organization, holding the record for most annual U.S. patents generated by a business (as of 2020) for 28 consecutive years. Inventions by IBM include the automated teller machine (ATM), the floppy disk, the hard disk drive, the magnetic stripe card, the relational database, the SQL programming language, the UPC barcode, and dynamic random-access memory (DRAM). The IBM mainframe, exemplified by the System/360, was the dominant computing platform during the 1960s and 1970s.",
  sector: "TECHNOLOGY",
  product_type:,
  esg_score: 993,
  er_score: 555,
  sr_score: 160,
  gr_score: 278
